version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: eventure-mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_AUTH_DB=$MONGO_AUTH_DB
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_DB_USERNAME=$MONGO_DB_USERNAME
      - MONGO_DB_PASSWORD=$MONGO_DB_PASSWORD
    volumes:
      - $MONGO_DATA_HOST_PATH:/data/db
      - $MONGO_LOG_HOST_PATH:/var/log/mongodb
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - main-network
    command: [ "--bind_ip", "0.0.0.0" ]
  web:
    build:
      context: .
      dockerfile: Dockerfile
    platform: 'linux/amd64'
    image: eventure-spring
    container_name: eventure-spring
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=$APP_NAME
      - ACCESS_KEY_ID=$ACCESS_KEY_ID
      - SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY
      - BUCKET_NAME=$BUCKET_NAME
    networks:
      - main-network
networks:
  main-network:
    external:
      name: $NETWORK_NAME